### ISSUE TITLE
crash on ValueError: time data u'Oct 13, 2016 18:44:48' does not match format '%b %d, %Y %H:%M:%S'

### ISSUE THREAD

**Issue by matkoniecz** [astronomersiva/satellite-passes-notifier#10]
```
python2 iridiumFetch.py 
Traceback (most recent call last):
  File "iridiumFetch.py", line 96, in <module>
    (start, intensity, loc) = parseRow(row)
  File "iridiumFetch.py", line 44, in parseRow
    start = datetime(*strptime(dtStr, '%b %d, %Y %H:%M:%S')[0:7])
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data u'Oct 13, 2016 18:44:48' does not match format '%b %d, %Y %H:%M:%S'
```

**Comment by matkoniecz** [comment]
Going by comment

> # Since Heavens Above stopped including the year in the flare
> # dates

it seems that they changed it back. Unfortunately, https://github.com/astronomersiva/satellite-passes-notifier/commit/1d8d63b4806438857b162092e95e3ae3aad18bd5 relevant file was fully commited so it will not be just revert

**Comment by matkoniecz** [comment]
This is a bit weird. Removing `import pynotify` fixes this issue (<s>and breaks different, later part of program</s>).

To reproduce run

```
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from datetime import datetime
import pynotify

datetime.strptime("Oct 13, 2016 18:44:48", "%b %d, %Y %H:%M:%S")
```

**Comment by matkoniecz** [comment]
http://stackoverflow.com/questions/10402304/pynotify-screws-up-datetime-why helped

```
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from datetime import datetime
import locale

print locale.getlocale()
datetime.strptime("Oct 13, 2016 18:44:48", "%b %d, %Y %H:%M:%S")

import pynotify

print locale.getlocale()
datetime.strptime("Oct 13, 2016 18:44:48", "%b %d, %Y %H:%M:%S")
```

gives for me

```
(None, None)
('en_US', 'UTF-8')
Traceback (most recent call last):
  File "date.py", line 13, in <module>
    datetime.strptime("Oct 13, 2016 18:44:48", "%b %d, %Y %H:%M:%S")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Oct 13, 2016 18:44:48' does not match format '%b %d, %Y %H:%M:%S'
```
